# Generated by Django 4.2.4 on 2023-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertisements/', verbose_name='изображение'),
        ),
    ]
